on: [push, pull_request]
name: Build & publish
jobs:
  build:
    if: ${{ !contains(forge.event.head_commit.message, 'skip ci') }}
    runs-on: github-latest
    env:
      RELEASE_BRANCH: ${{ startsWith(forge.ref, 'refs/heads/develop-') || startsWith(forge.ref, 'refs/heads/release-') }}
    steps:
      - name: Check out source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip build
          apt-get update -y
          apt-get install -y flex bison ccache cmake
      - name: Set up caching
        uses: actions/cache@v4
        with:
          path: ~/.cache/ccache
          key: yosys-${{ hashFiles('yosys-src', 'SymbiYosys-src', 'build.sh') }}
          restore-keys: |
            yosys-${{ hashFiles('yosys-src', 'SymbiYosys-src', 'build.sh') }}
            yosys-
      - name: Set up ccache
        run: |
          ccache --max-size=5G -z
      - name: Build WASM binaries
        run: |
          MAKEFLAGS=-j$(nproc) ./build.sh
      - name: Build Python artifact
        run: |
          ./package-pypi.sh
      - name: Upload Python artifact
        uses: forgejo/upload-artifact@v4
        with:
          name: dist-pypi
          path: pypi/dist/
      - name: Build JavaScript artifact
        run: |
          ./package-npmjs.sh
          cp npmjs/test/test_api.mjs npmjs/dist/
      - name: Upload JavaScript artifact
        uses: forgejo/upload-artifact@v4
        with:
          name: dist-npmjs
          path: npmjs/dist/
      - name: Print ccache statistics
        run: |
          ccache -s
  test-python:
    needs: build
    runs-on: github-latest
    strategy:
      matrix:
        python-version:
        - '3.9'
        - '3.10'
        - '3.11'
        - '3.12'
        - '3.13'
        - '3.14'
        - '3.15-dev'
    steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Download Python artifact
      uses: forgejo/download-artifact@v4
      with:
        name: dist-pypi
        path: dist/
    - name: Test Python artifact
      run: |
        pip install dist/*.whl
        yowasp-yosys --help
        yowasp-yosys -p 'slang_version'
        yowasp-sby --help
        yowasp-yosys-smtbmc --help
        yowasp-yosys-witness --help
  test-javascript:
    needs: build
    runs-on: github-latest
    strategy:
      matrix:
        node-version:
          - 'v18.x'
          - 'v20.x'
          - 'v22.x'
          - 'v24.x'
    steps:
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - name: Download JavaScript artifact
      uses: forgejo/download-artifact@v4
      with:
        name: dist-npmjs
        path: dist/
    - name: Test JavaScript artifact
      run: |
        npm install ./dist/*.tgz
        node dist/test_api.mjs
  check:
    needs: [test-python, test-javascript]
    runs-on: github-latest
    steps:
      - run: true
  publish-python:
    needs: check
    runs-on: github-latest
    if: ${{ !contains(forge.event.head_commit.message, 'skip py') }}
    steps:
    - name: Download Python artifact
      uses: forgejo/download-artifact@v4
      with:
        name: dist-pypi
        path: dist/
    - name: Publish wheels to Test PyPI
      if: ${{ forge.event_name == 'push' && startsWith(forge.ref, 'refs/heads/develop') }}
      uses: https://github.com/pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/
        attestations: false
        password: ${{ secrets.TEST_PYPI_TOKEN }}
    - name: Publish wheels to PyPI
      if: ${{ forge.event_name == 'push' && startsWith(forge.ref, 'refs/heads/release') }}
      uses: https://github.com/pypa/gh-action-pypi-publish@release/v1
      with:
        attestations: false
        password: ${{ secrets.PYPI_TOKEN }}
  publish-javascript:
    needs: check
    runs-on: github-latest
    if: ${{ !contains(forge.event.head_commit.message, 'skip js') }}
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        registry-url: 'https://registry.npmjs.org'
    - name: Update npm
      run: npm install -g npm@latest
    - name: Download JavaScript artifact
      uses: forgejo/download-artifact@v4
      with:
        name: dist-npmjs
        path: dist/
    - name: Publish package to NPM (dry run)
      if: ${{ forge.event_name == 'push' && startsWith(forge.ref, 'refs/heads/develop') }}
      run: npm publish $(find dist -name *.tgz -printf 'file:%p ') ${{ forge.ref == 'refs/heads/release' && '--tag latest' || '--tag release' }} --dry-run
    - name: Publish package to NPM
      if: ${{ forge.event_name == 'push' && startsWith(forge.ref, 'refs/heads/release') }}
      run: npm publish $(find dist -name *.tgz -printf 'file:%p ') ${{ forge.ref == 'refs/heads/release' && '--tag latest' || '--tag release' }}
  release:
    needs: check
    runs-on: github-latest
    if: ${{ contains(forge.event.head_commit.message, 'autorelease') && forge.event_name == 'push' && startsWith(forge.ref, 'refs/heads/develop') }}
    steps:
      - name: Check out source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PUSH_TOKEN }}
      - name: Update release branch
        run: |
          release_branch=${{ forge.ref }}
          release_branch=${release_branch/develop/release}
          git push origin HEAD:${release_branch}
